data:
  audioset:
    balanced_only: true
  preprocess:
    # Unit duration in seconds for one audio segment
    unit_sec: 0.95
    # FFT parameters
    sample_rate: 16000
    n_fft: 1024
    win_length: 1024
    hop_length: 160
    n_mels: 64
    f_min: 60
    f_max: 7800
  transform:
    # Transform raw waveform
    min_rate: 0.5
    max_rate: 1.5
    ts_p: 0.6
    min_semitones: -7
    max_semitones: 7
    ps_p: 0.6
    # Transform lms
    mixup: true
    gaussnoise: false
    mixup_ratio: 0.4
    gaussnoise_ratio: 0.4
  dataloader:
    num_workers: 4
model:
  encoder:
    type: transformer
    size: base
    ps: [16,16]
    mask_ratio: 0.75
    latent: cls
  projection:
    sizes:
  lambd: 5.0e-3
optimizer:
  type: adamw
  base_lr: 1.0e-4
  final_lr: 1.0e-6
  warmup_epochs: 1
  weight_decay: 0.04
  final_weight_decay: 0.4
  epochs: 10
  batch_size_per_gpu: 512
meta:
  distributed:
  seed: 32
  use_fp16: false
checkpoint:
  print_it: 100
  save_epoch: 1
  ckpt_path:
logging:
  log_dir: checkpoint/{}
dist_url: env://
dist_init: file