data:
  audioset:
    balanced_only: false
    twohundredk_only: true
  preprocess:
    # Unit duration in seconds for one audio segment
    unit_sec: 0.95
    # FFT parameters
    sample_rate: 16000
    n_fft: 1024
    win_length: 1024
    hop_length: 160
    n_mels: 64
    f_min: 60
    f_max: 7800
    # [mean, std], for audioset: [-0.8294, 4.6230]
    norm_stats: [-0.8294, 4.6230]
  transform:
    # Transform lms
    mixup_ratio: 0.4
  dataloader:
    num_workers: 10
    npy: False
model:
  encoder:
    type: resnet50
  projection:
    sizes: # [2048, 8192, 8192, 8192]
    projector_x: 4
  lambd: 5.0e-3
optimizer:
  epochs: 40
  warmup_epochs: 6
  batch_size_per_gpu: 256
  lr_weights: 0.2
  lr_biases: 0.0048
meta:
  distributed:
  seed: 33
  use_fp16: false
checkpoint:
  print_it: 20
  save_epoch_it: 10
  ckpt_path:
logging:
  log_dir: checkpoint/{}
knn:
  track_knn: true
  track_knn_it: 1
  k: 200
  T: 0.07
  num_classes: 527
dist_url: env://
