weight_file:
task: audioset
num_classes: 527
val_freq: 5
data:
  audioset:
    balanced_only: true
    twohundredk_only: false
  preprocess:
    # Unit duration in seconds for one audio segment
    unit_sec: 0.95
    # FFT parameters
    sample_rate: 16000
    n_fft: 1024
    win_length: 1024
    hop_length: 160
    n_mels: 64
    f_min: 60
    f_max: 7800
    # [mean, std], for audioset: [-0.8294, 4.6230]
    norm_stats: [-0.8294, 4.6230]
  dataloader:
    num_workers: 10
    npy: False
model:
  encoder:
    latent: cls
optimizer:
  type: sgd
  lr: 0.1
  epochs: 100
  batch_size_per_gpu: 256
  normalize: true
meta:
  distributed: 
  seed: 32
  use_fp16: false
checkpoint:
  print_it: 10
logging:
  log_dir: 
dist_url: env://