data:
  audioset:
    balanced_only: false
    twohundredk_only: true
  preprocess:
    # Unit duration in seconds for one audio segment
    unit_sec: 0.95
    # FFT parameters
    sample_rate: 16000
    n_fft: 1024
    win_length: 1024
    hop_length: 160
    n_mels: 64
    f_min: 60
    f_max: 7800
    # [mean, std], for audioset: [-0.8294, 4.6230]
    norm_stats: [-0.8294, 4.6230]
    # Shape of log mel spectrogram [F, T]
    shape: [64, 96]
  transform:
    # Transform lms
    mixup_ratio: 0.4
  dataloader:
    num_workers: 10
    npy: False
model:
  encoder:
    type: byola-audiontt
    feature_d: 2048
  projection:
    proj_size: 256
    proj_dim: 4096
  ema_decay: 0.99
optimizer:
  type: adam
  lr: 3.0e-4
  epochs: 40
  batch_size_per_gpu: 128
meta:
  distributed:
  seed: 32
  use_fp16: false
checkpoint:
  print_it: 20
  save_epoch_it: 5
  ckpt_path:
logging:
  log_dir: byola/checkpoint/{}
knn:
  track_knn: true
  track_knn_it: 1
  k: 200
  T: 0.07
  num_classes: 527
dist_url: env://
